### ISSUE TITLE
Binary SMA component

### ISSUE THREAD

**Issue by cars10w** [MewsSystems/fiscalization-germany#21]
Hi there,

just found your library that interacts with Fiskaly to report invoices etc. which is pretty cool.

But I have a question regarding the SMA component, which (to my understanding) has to be run in the operational environment of the POS system.

Let me quote https://developer.fiskaly.com/en/docs/interfaces :

"The Protection Profile specified by BSI requires that a **local SMA component executed in the operational environment** of the POS system takes over the incrementation of the transaction counter and the establishment of the trusted channel to the remotely connected CSP component."

This SMA component is within the binary DLL called **fiskaly-client** (see https://developer.fiskaly.com/downloads) and we are forced to use it in order to be compliant with the law and government requirements. Since that binary went through the appropriate certification.

So I could replace Fiskaly's own .NET SDK (which is just a thin wrapper around the fiskaly-client) with my own implementation (or your library), but I can not ignore the fiskaly-client itself.

Do you have any further information and what is your opinion about this topic?

Thanks in advance and best regards!

**Comment by KaliCZ** [comment]
@cars10w Hey, 

We host our services in the cloud, so it's fairly difficult for us to host the code in operating system of our software.

Based on [the documentation they provided](https://developer.fiskaly.com/api/kassensichv/v1/#section/Quick-Start) our understanding is that we can just use their API directly and the rest is handled by Fiskaly servers. And their client is just a wrapper like you said. We believe that the local SMA component doesn't need to be their component, but it can be anything that guarantees that transactions have unique numbers. And our software contains such code.

Our PM has communicated with Fiskaly directly and at no point did they raise to use that we wouldn't in fact be compliant with our approach.

Best Regards

**Comment by cars10w** [comment]
Thanks a lot for your feedback!
